apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookit
spec:
  selector:
    matchLabels:
      app: bookit
  template:
    metadata:
      labels:
        app: bookit
    spec:
      containers:
      - name: bookit
        image: rafshari/bookit:v1.0.0
        resources:
          limits:
            memory: 100M
            ephemeral-storage: 0.1G
            cpu: 100m
          requests:
            memory: 100M
            ephemeral-storage: 0.1G
            cpu: 100m
        ports:
        - containerPort: 3000
          name: server-port
 
---
apiVersion: v1
kind: Service
metadata:
  name: bookit
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: app-port
  selector:
    app: bookit
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route 
metadata: 
  name: bookit-route
  namespace: eshop
spec:
  host: bookit-eshop.apps.ir-thr-ba1.arvan.run
  port:
    targetPort: 30000
  tls: 
    insecureEdgeTerminationPolicy: Redirect
    termination: edge 
  to: 
    kind: service 
    name: bookit

