version: '3'

services:
  app:
    image: rafshari/bookit:v3.0.0
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      


# version: '3'

# services:
#   app:
#     image: rafshari/bookit:v1.0.0
#     build: .
#     ports:
#       - 3000:3000